export const ANIMALS_LOADING = 'ANIMALS_LOADING';
export const ADD_ANIMALS = 'ADD_ANIMALS';
export const ANIMALS_FAILED = 'ANIMALS_FAILED';

export const SHOPPING_PARTNERS_LOADING = 'SHOPPING_PARTNERS_LOADING';
export const ADD_SHOPPING_PARTNERS = 'ADD_SHOPPING_PARTNERS';
export const SHOPPING_PARTNERS_FAILED = 'SHOPPING_PARTNERS_FAILED';

export const PARTNERS_LOADING = 'PARTNERS_LOADING';
export const ADD_PARTNERS = 'ADD_PARTNERS';
export const PARTNERS_FAILED = 'PARTNERS_FAILED';

export const ADD_FAVORITE = 'ADD_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE'; 